export const APP_START = 'boilerplate/app_start';
export const IS_LOADING_FILESHARE_DATA = 'IS_LOADING_FILESHARE_DATA';
export const IS_LOADING_CREATE_FILESHARE = 'IS_LOADING_CREATE_FILESHARE';
export const FILESHARE_DATA = 'FILESHARE_DATA';
export const ADD_FILESHARE_DATA = 'ADD_FILESHARE_DATA';
export const SHAREDFILE_DATA = 'SHAREDFILE_DATA';
export const CHANGE_LOCALE = 'change_locale';
