export const IS_LOADING_FILESHARE_DATA = 'IS_LOADING_FILESHARE_DATA';
export const IS_LOADING_CREATE_FILESHARE = 'IS_LOADING_CREATE_FILESHARE';
export const FILESHARE_DATA = 'FILESHARE_DATA';
export const ADD_FILESHARE_DATA = 'ADD_FILESHARE_DATA';
export const SHAREDFILE_DATA = 'SHAREDFILE_DATA';
export const FEIL_DETAIL_DATA = 'FEIL_DETAIL_DATA';
export const SHARED_FILE_DETAIL_DATA = 'SHARED_FILE_DETAIL_DATA';