export const CREATE_GROUP = 'CREATE_GROUP';
export const IS_LOADING_CREATE_GROUP = 'IS_LOADING_CREATE_GROUP';

export const GET_GROUP_LIST = 'GET_GROUP_LIST';
export const IS_LOADING_GET_GROUP_LIST = 'IS_LOADING_GET_GROUP_LIST';

export const GET_GROUP_DETAIL = 'GET_GROUP_DETAIL';
export const IS_LOADING_GET_GROUP_DETAIL = 'IS_LOADING_GET_GROUP_DETAIL';

export const REMOVE_GROUP_MEMBER = 'REMOVE_GROUP_MEMBER';
export const ADD_GROUP_MEMBER = 'ADD_GROUP_MEMBER';

export const SET_GROUP_ALERT = 'SET_GROUP_ALERT';
export const REMOVE_GROUP_ALERT = 'REMOVE_GROUP_ALERT';

export const SET_SHOW_GROUP_DETAIL_MODAL = 'SET_SHOW_GROUP_DETAIL_MODAL';

export const SET_ADD_MEMBER_FROM = 'SET_ADD_MEMBER_FROM';

export const CREATE_GROUP_MEMBERSHIP = 'CREATE_GROUP_MEMBERSHIP';
export const IS_LOADING_CREATE_GROUP_MEMBERSHIP =
  'IS_LOADING_CREATE_GROUP_MEMBERSHIP';

export const GET_GROUP_MEMBERSHIP = 'GET_GROUP_MEMBERSHIP';
export const IS_LOADING_GET_GROUP_MEMBERSHIP =
  'IS_LOADING_GET_GROUP_MEMBERSHIP';

export const SET_AMERA_GROUP_SECURITY = 'SET_AMERA_GROUP_SECURITY';
