export const MEMBER = 'MEMBER';
export const MEMBER_LOGIN_SUCCEEDED = 'MEMBER_LOGIN_SUCCEEDED';
export const MEMBER_LOGIN_FAILED = 'MEMBER_LOGIN_FAILED';
export const GET_MEMBER_DATA_SUCCEEDED = 'GET_MEMBER_DATA_SUCCEEDED';
export const GET_MEMBER_DATA_FAILED = 'GET_MEMBER_DATA_FAILED';
export const MEMBER_LOGOUT_SUCCEEDED = 'MEMBER_LOGOUT_SUCCEEDED';
export const MEMBER_LOGOUT_FAILED = 'MEMBER_LOGOUT_FAILED';

export const SAVE_SIGN_UP_SESSION = 'SAVE_SIGN_UP_SESSION';
export const CLEAR_SIGN_UP_SESSION = 'CLEAR_SIGN_UP_SESSION';

export const GET_MEMBER_LOCATION_INFO_START = 'GET_MEMBER_LOCATION_INFO_START';
export const GET_MEMBER_LOCATION_INFO_SUCCEEDED =
  'GET_MEMBER_LOCATION_INFO_SUCCEEDED';
export const GET_MEMBER_LOCATION_INFO_FAILED =
  'GET_MEMBER_LOCATION_INFO_FAILED';
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_LOAD_SUCCESS = 'MEMBERS_LOAD_SUCCESS';
